{
	"version": 1663001976,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg-sheet0.png",
		"images/btn_comecar-sheet0.png",
		"images/logoquizinicial-sheet0.png",
		"images/logoes-sheet0.png",
		"images/int1-sheet0.png",
		"images/int2-sheet0.png",
		"images/ruth-sheet0.png",
		"images/caixapergunta-sheet0.png",
		"images/logoquiz-sheet0.png",
		"images/qustao-sheet0.png",
		"images/qustao-sheet1.png",
		"images/qustao-sheet2.png",
		"images/perguntas-sheet0.png",
		"images/cx_respos-sheet0.png",
		"images/cx_respos-sheet1.png",
		"images/cx_respos-sheet2.png",
		"images/respostas-sheet0.png",
		"images/respostas-sheet1.png",
		"images/btn_jogar_novament-sheet0.png",
		"images/mais_final-sheet0.png",
		"images/mais_final-sheet1.png",
		"images/mais_final-sheet2.png",
		"images/mais_final-sheet3.png",
		"images/mais_final-sheet4.png",
		"images/botaovoltar-sheet0.png",
		"images/botaofecharover-sheet0.png",
		"images/botaofecharover-sheet1.png",
		"media/10- abacaxi-xi-xi base_bg.ogg",
		"media/erro a.ogg",
		"media/menu click acerto.ogg",
		"media/vencedor.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}